### ISSUE TITLE
opus decoding error

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/dataset-viewer#2584] opened 2024-03-13 12:07 UTC
see https://huggingface.co/datasets/stable-speech/mls_eng_10k/discussions/1#65ef6e9d440a5fc3d94a40ad

To fix this maybe we should pin `soundfile` library to `>=1.0.31` (first version that supported opus) like [we do in `datasets` library](https://github.com/huggingface/datasets/blob/main/src/datasets/config.py#L144).

**Comment by polinaeterna** [comment] 2024-03-13 12:08
cc @severo 

(I didn't even know that we rely on `ffmpeg`, if i remember correctly, it wasn't working well with opus a year ago. )

**Comment by severo** [comment] 2024-03-13 14:33
previous issue: https://github.com/huggingface/datasets-server/issues/194

**Comment by severo** [comment] 2024-03-13 15:08
See also https://github.com/huggingface/datasets-server/pull/608/commits/dadb8f207d826ce4d37f0e51ebaaeaa474ab0379, where we replaced compilation of libsndfile1 with installation from the repositories, since the distributed version at that point supported opus.

**Comment by severo** [comment] 2024-03-13 15:09
Currently, the workers have:

```
I have no name!@prod-datasets-server-worker-medium-cbf4c8846-4vm5r:/src/services/worker$ apt-cache show libsndfile1
Package: libsndfile1
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 574
Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Architecture: amd64
Multi-Arch: same
Source: libsndfile
Version: 1.2.0-1
Depends: libc6 (>= 2.33), libflac12 (>= 1.3.0), libmp3lame0 (>= 3.100), libmpg123-0 (>= 1.28.0), libogg0 (>= 1.3.0), libopus0 (>= 1.1), libvorbis0a (>= 1.2.3), libvorbisenc2 (>= 1.1.2)
Description: Library for reading/writing audio files
 libsndfile is a library of C routines for reading and writing files containing
 sampled audio data.
 .
 Various versions of WAV (integer, floating point, GSM, and compressed formats);
 Microsoft PCM, A-law and u-law formats; AIFF, AIFC and RIFX; various AU/SND
 formats (Sun/NeXT, Dec AU, G721 and G723 ADPCM); RAW header-less PCM files;
 Amiga IFF/8SVX/16SV PCM files; Ensoniq PARIS  (.PAF); Apple's Core Audio Format
 (CAF) and others.
Description-md5: 67b723b50c9aa944fba48e79d51e9d5c
Homepage: http://www.mega-nerd.com/libsndfile/
```

**Comment by severo** [comment] 2024-03-14 10:07
So: it does not seem to be an issue with the versions of soundfile / libsndfile1.

I unassign myself, as I have no particular clues about it. @huggingface/datasets-server feel free to pick it.

**Comment by ylacombe** [comment] 2024-04-05 08:07
Any updates on this ?

**Comment by ylacombe** [comment] 2024-04-15 13:19
Up! It would be very helpful to have this!

**Comment by albertvillanova** [comment] 2024-04-15 13:54
Hello, it seems there was an issue with the new 0.12 OPUS format that had to be fixed on the libsndfile.
- See issue: https://github.com/libsndfile/libsndfile/issues/888
- See fixing PR: https://github.com/libsndfile/libsndfile/pull/926

The fix was released on libsndfile-1.2.2.

Therefore, I think the only solution in our part would be to force using libsndfile-1.2.2 (now we use 1.2.0).
- The problem is that this version is not officially distributed by Linux package manager yet.
  - @polinaeterna do you remember if we can ask them to update their distributed version, as the last time we had an analogue issue? If I remember correctly, I think you contacted them.

**Comment by albertvillanova** [comment] 2024-04-15 13:57
Yes, if we have no other option... :disappointed:

**Comment by albertvillanova** [comment] 2024-04-15 14:02
Maybe we are lucky? :crossed_fingers: https://launchpad.net/ubuntu/+source/libsndfile/1.2.2-1ubuntu5

**Comment by albertvillanova** [comment] 2024-04-15 14:03
Could we check? @severo I don't know how...

**Comment by severo** [comment] 2024-04-15 14:06
Maybe there is nothing to do, because we don't pin the libsndfile1 version: https://github.dev/huggingface/dataset-viewer/blob/c355f4bbbd82a62abbb5a7d927e403659c18ebbd/services/worker/Dockerfile#L19-L20

Maybe add the problematic opus file to the services/worker tests, and ensure we can process it

**Comment by albertvillanova** [comment] 2024-04-16 06:44
Unfortunately, the problem persists.

**Comment by severo** [comment] 2024-05-02 11:31
Thanks. It's also what we were doing before:

https://github.com/huggingface/dataset-viewer/blob/a22b5fd967ff3cc0c0d52615dfd73455a73b966d/services/worker/Dockerfile#L16-L33

Should we restore this @polinaeterna @albertvillanova?

**Comment by ylacombe** [comment] 2024-05-09 12:18
Hey there, any news on this? let me know if I can help!

**Comment by albertvillanova** [comment] 2024-05-10 09:18
Hi, I can restore the building of libsndfile from source as we did before.

**Comment by albertvillanova** [comment] 2024-05-15 15:38
After a more detailed investigation and when trying to implement a test, I discovered that the error is not caused by `libsndfile1` but by `pydub` when it calls `ffmpeg`. See insightful comment by @severo: https://huggingface.co/datasets/parler-tts/mls_eng_10k/discussions/1#65ef6e9d440a5fc3d94a40ad
> The reason is:
```
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 
...
Unknown input format: 'opus'
```

I am opening another PR with a test that raises that error and with a proposed fix. Let's see if that fixes the issue.

**Closed** 2024-05-16 04:38 UTC
Labels: bug, P1

**Comment by severo** [comment] 2024-05-16 10:04
To get the list of affected datasets in the database:

```js
db.cachedResponsesBlue.aggregate([
  {
    $match: {
      error_code: "RowsPostProcessingError",
      "details.cause_exception": "CouldntDecodeError",
      "details.cause_message": { $regex: "Unknown input format: 'opus'" },
    },
  },
  {
    $group: {
      _id: "$dataset",
    },
  },
]);
```

I refreshed all of them

**Comment by severo** [comment] 2024-05-16 11:28
Finally, I refreshed all of:
```
{
      error_code: "RowsPostProcessingError",
      "details.cause_exception": "CouldntDecodeError",
}
```

which is a bit more than 500 datasets. Nearly all the errors have been fixed (though it's still in progress). Still some `Invalid data found when processing input`
